# Adapter
ADAPTER_SIDE=38
ADAPTER_SIDE=38
ADAPTER_HOLE_TO_HOLE=30
ADAPTER_HOLE_TO_SIDE=(ADAPTER_SIDE-ADAPTER_HOLE_TO_HOLE)/2
# Lens ring
CS_LENS_RING_OD=36
CS_LENS_RING_ID=25.1
CS_LENS_RING_NUT_OFFSET=(CS_LENS_RING_OD-CS_LENS_RING_ID)/4+CS_LENS_RING_ID/2
# Nuts
M2_5_NUT_D = 5.5+0.3
M2_5_NUT_H = 2+0.2
# DON'T KNOW, GUESSING
M2_NUT_H = 3
M2_NUT_D = 4.4

SENSOR_BASE_HEIGHT = 0.3 # This is more of a guess then anything

CS_MOUNT_FOCAL_DISTANCE = 12.526

# GPIO
GPIO_LENGTH = 51
GPIO_WIDTH = 5.4
GPIO_OFFSET = 1
